### ISSUE TITLE
Recommend using //todo comment

### ISSUE THREAD

**Issue by arunjeetsingh** [MSiccDev/StringEncryptionHelper_WinUniversal81#3]
See here: http://blogs.msdn.com/b/zainnab/archive/2013/08/15/visual-studio-2013-todo-comments-and-custom-tokens-in-the-task-list.aspx. I'd recommend using a comment like **//todo Add pre-shared key** in the PreSharedKey method to let developers know they need to do work here.

**Comment by MSiccDev** [comment]
implemented.
